#line 2 "scanner.cpp"

#line 4 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer pfl__create_buffer
#define yy_delete_buffer pfl__delete_buffer
#define yy_flex_debug pfl__flex_debug
#define yy_init_buffer pfl__init_buffer
#define yy_flush_buffer pfl__flush_buffer
#define yy_load_buffer_state pfl__load_buffer_state
#define yy_switch_to_buffer pfl__switch_to_buffer
#define yyin pfl_in
#define yyleng pfl_leng
#define yylex pfl_lex
#define yylineno pfl_lineno
#define yyout pfl_out
#define yyrestart pfl_restart
#define yytext pfl_text
#define yywrap pfl_wrap
#define yyalloc pfl_alloc
#define yyrealloc pfl_realloc
#define yyfree pfl_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE pfl_restart(pfl_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int pfl_leng;

extern FILE *pfl_in, *pfl_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up pfl_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up pfl_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via pfl_restart()), so that the user can continue scanning by
	 * just pointing pfl_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when pfl_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int pfl_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow pfl_wrap()'s to do buffer switches
 * instead of setting up a fresh pfl_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void pfl_restart (FILE *input_file  );
void pfl__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE pfl__create_buffer (FILE *file,int size  );
void pfl__delete_buffer (YY_BUFFER_STATE b  );
void pfl__flush_buffer (YY_BUFFER_STATE b  );
void pfl_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void pfl_pop_buffer_state (void );

static void pfl_ensure_buffer_stack (void );
static void pfl__load_buffer_state (void );
static void pfl__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER pfl__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE pfl__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE pfl__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE pfl__scan_bytes (yyconst char *bytes,int len  );

void *pfl_alloc (yy_size_t  );
void *pfl_realloc (void *,yy_size_t  );
void pfl_free (void *  );

#define yy_new_buffer pfl__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        pfl_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pfl__create_buffer(pfl_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        pfl_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pfl__create_buffer(pfl_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define pfl_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *pfl_in = (FILE *) 0, *pfl_out = (FILE *) 0;

typedef int yy_state_type;

extern int pfl_lineno;

int pfl_lineno = 1;

extern char *pfl_text;
#define yytext_ptr pfl_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up pfl_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	pfl_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 62
#define YY_END_OF_BUFFER 63
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[179] =
    {   0,
        0,    0,   63,   61,   60,   56,   44,   61,   36,   54,
       55,   34,   30,   57,   32,    1,    1,   51,   48,   61,
       47,   33,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   11,   22,   22,   52,   53,   38,   58,   37,
       59,   39,   46,    0,   42,   35,   31,    0,    1,    0,
        0,   40,   50,   45,   49,   41,    0,    0,    0,   22,
       22,   22,   22,   22,   22,   22,   16,   22,   22,   12,
       14,   22,   22,   22,   43,    0,   21,    0,    1,    0,
        2,   24,    0,   23,   13,   18,   22,   22,   22,   22,
       22,   15,   22,   22,   22,    0,    0,    0,   24,   26,

       27,   23,   22,   22,   22,   22,   22,   22,   10,   22,
       22,   22,    0,    0,   25,   26,   22,   22,   22,   22,
       22,   17,   22,   22,   22,    0,    0,   28,   25,   22,
       22,   22,   22,   22,    9,   22,   22,   29,    0,   22,
       22,   22,   22,    4,   22,   22,    0,   22,    5,   22,
       22,   22,   19,    0,   22,   22,   20,   22,    0,   22,
       22,   22,    0,   22,   22,   22,    0,   22,   22,    8,
        0,    6,    7,    0,    0,    0,    3,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,    1,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,    1,   19,
       20,   21,   22,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   29,   32,   33,   34,   35,   36,   37,
       29,   38,   39,   40,   41,   42,   29,   43,   44,   29,
       45,    1,   46,   47,   48,    1,   49,   24,   50,   51,

       52,   53,   29,   54,   55,   29,   56,   57,   58,   59,
       60,   61,   29,   62,   63,   64,   65,   66,   29,   67,
       68,   29,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[73] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        4,    1,    1,    1,    5,    6,    6,    1,    1,    1,
        1,    1,    7,    7,    7,    7,    7,    7,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    9,    8,    1,    1,    1,   10,    7,    7,
        7,    7,    7,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    9,    8,    1,    1,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[200] =
    {   0,
        0,    0,  216,  809,  809,  809,  188,    0,  198,  809,
      809,  186,  175,  809,  809,   58,   61,  809,   60,  164,
       61,  809,  122,  175,   60,   41,   45,   78,   83,   92,
       80,  145,  119,  116,  147,  809,  809,  809,  809,   96,
      809,  809,  809,  158,  809,  809,  809,   89,   96,  135,
        0,  809,  809,  809,  809,  809,  134,  129,    0,  152,
      154,  203,  178,  198,  204,  223,  224,  225,  235,  238,
      244,  255,  262,  271,  809,  126,  809,  161,  205,    0,
        0,  268,    0,  113,  280,  281,  283,  293,  290,  296,
      309,  307,  308,  329,  330,  105,    0,    0,  334,    0,

      809,  108,  332,  353,  362,  371,  373,  372,  385,  386,
      397,  398,  339,   99,   91,    0,  399,  409,  421,  422,
      434,  423,  432,  441,  447,  119,    0,  809,   89,  458,
      459,  468,  477,  480,  490,  492,  499,  178,    0,  505,
      523,  524,  526,  535,  548,  550,   79,  549,  559,  572,
      574,  581,  583,    0,  584,  598,  601,  607,    0,  621,
      608,  619,   74,  622,  636,  638,    0,  659,  662,  668,
        0,  674,  683,   70,    0,    0,  809,  809,  725,  731,
      738,  748,  753,  754,  758,  759,  765,  770,  771,  775,
      782,  787,  789,  791,  793,  795,  797,  799,  801

    } ;

static yyconst flex_int16_t yy_def[200] =
    {   0,
      178,    1,  178,  178,  178,  178,  178,  179,  178,  178,
      178,  178,  178,  178,  178,  180,  180,  178,  178,  178,
      178,  178,  181,  181,   24,   24,   24,  181,  181,  181,
      181,  181,  181,  181,  181,  178,  178,  178,  178,  178,
      178,  178,  178,  182,  178,  178,  178,  178,  178,  178,
      183,  178,  178,  178,  178,  178,  178,  178,  184,  181,
      181,  181,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  178,  182,  178,  178,  178,  185,
      183,  178,  186,  187,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  178,  188,  189,  178,  190,

      178,  187,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  178,  178,  191,  190,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  178,  192,  178,  191,  181,
      181,  181,  181,  181,  181,  181,  181,  178,  193,  181,
      181,  181,  181,  181,  181,  181,  178,  181,  181,  181,
      181,  181,  181,  194,  181,  181,  181,  181,  195,  181,
      181,  181,  178,  181,  181,  181,  196,  181,  181,  181,
      197,  181,  181,  178,  198,  199,  178,    0,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178

    } ;

static yyconst flex_int16_t yy_nxt[882] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,   13,   14,   15,    4,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   24,   26,   27,   28,   28,
       29,   28,   28,   30,   31,   32,   33,   34,   28,   35,
       28,   28,   28,   28,   36,   37,   38,    4,   23,   25,
       24,   26,   27,   28,   29,   28,   28,   30,   31,   32,
       33,   34,   28,   35,   28,   28,   28,   28,   39,   40,
       41,   42,   48,   49,   49,   48,   49,   49,   52,   53,
       55,   56,   63,   65,   57,   66,   57,  175,   58,   57,
       58,  167,   59,   58,   59,   64,  154,   59,   57,  128,

       51,  128,   58,  178,   78,   78,   59,   65,   63,   66,
       48,   79,   79,   80,   68,   69,  127,   67,  101,   64,
      113,  113,   57,  101,   51,   57,   58,  178,   57,   58,
       59,   77,   58,   59,  138,  138,   59,   60,   60,   69,
       68,   67,   73,   83,   60,   60,   60,   60,   60,   60,
       82,   57,   80,   57,   72,   58,   62,   58,   57,   59,
       57,   59,   58,   77,   58,   75,   59,   73,   59,   80,
       60,   60,   60,   60,   60,   96,   78,   78,   72,   70,
       62,   57,   71,   54,   57,   58,   47,   74,   58,   59,
       60,   60,   59,  138,  138,   80,   46,   60,   60,   60,

       60,   60,   60,   70,   57,   45,   71,   43,   58,   57,
       57,   74,   59,   58,   58,  178,   87,   59,   59,   48,
       79,   79,  178,   60,   60,   60,   60,   60,   85,   57,
       57,   57,   88,   58,   58,   58,  178,   59,   59,   59,
       87,   57,  178,   89,   57,   58,   86,  178,   58,   59,
       57,  178,   59,   85,   58,   90,   88,  178,   59,  178,
      178,   57,  178,  178,   91,   58,  178,   89,   57,   59,
       86,  178,   58,  178,   92,  178,   59,   57,  178,   90,
      178,   58,   98,   99,   99,   59,   57,   57,   91,   57,
       58,   58,   93,   58,   59,   59,   57,   59,   92,   57,

       58,   94,   57,   58,   59,   95,   58,   59,  178,  103,
       59,  178,  178,   57,   57,   57,   93,   58,   58,   58,
      178,   59,   59,   59,  178,   94,  178,  105,  106,   95,
      178,  178,  104,  107,  103,   57,   57,  108,   57,   58,
       58,  178,   58,   59,   59,  178,   59,  109,   98,   99,
       99,  105,  106,  126,  113,  113,  104,  178,  107,   57,
      178,  108,  178,   58,  112,  110,  178,   59,   57,  111,
      117,  109,   58,  178,  178,  118,   59,   57,   57,   57,
      178,   58,   58,   58,  119,   59,   59,   59,  112,  110,
      178,   57,   57,  111,  117,   58,   58,  120,  178,   59,

       59,  118,  121,   57,   57,   57,  122,   58,   58,   58,
      119,   59,   59,   59,  178,   57,  178,  123,  178,   58,
      178,  178,  120,   59,  125,  130,  121,   57,   57,   57,
      122,   58,   58,   58,  124,   59,   59,   59,   57,  131,
       57,  123,   58,  178,   58,  132,   59,   57,   59,  125,
      130,   58,  178,   57,  178,   59,  133,   58,  124,  178,
      134,   59,  178,  131,   57,   57,  178,  178,   58,   58,
      132,  135,   59,   59,   57,  136,  178,  178,   58,  137,
      133,  178,   59,   57,  178,  134,   57,   58,  178,  178,
       58,   59,  140,  141,   59,  135,   57,  178,   57,  136,

       58,  143,   58,  137,   59,   57,   59,  142,  178,   58,
      178,   57,  178,   59,  178,   58,  140,  141,  144,   59,
      178,  178,  178,  178,  178,  146,  143,  178,  145,   57,
       57,  142,   57,   58,   58,  178,   58,   59,   59,  178,
       59,   57,  144,  148,  178,   58,  178,  178,  151,   59,
      146,  150,  145,  178,   57,   57,   57,  178,   58,   58,
       58,  149,   59,   59,   59,   57,  178,  148,  178,   58,
      152,  178,  178,   59,  151,  153,  150,  178,   57,  155,
       57,  178,   58,  178,   58,  149,   59,   57,   59,   57,
       57,   58,  178,   58,   58,   59,  152,   59,   59,  178,

      153,  178,  156,  155,   57,  158,  178,   57,   58,  178,
      157,   58,   59,   57,   57,   59,  178,   58,   58,  178,
      178,   59,   59,  160,  161,   57,  156,   57,   57,   58,
      158,   58,   58,   59,  157,   59,   59,  178,  162,  178,
      165,  178,   57,  178,   57,  166,   58,  160,   58,  161,
       59,  164,   59,  178,  178,  178,  178,  178,  178,  178,
      178,  169,  162,  168,  165,   57,  178,  178,   57,   58,
      166,  178,   58,   59,   57,  164,   59,  170,   58,  178,
       57,  178,   59,  178,   58,  172,  169,  168,   59,   57,
      178,  178,  178,   58,  178,  178,  178,   59,  178,  178,

      173,  170,  178,  178,  178,  178,  178,  178,  178,  178,
      172,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  173,   44,  178,   44,   44,   44,
       44,   44,   44,   44,   44,   50,   50,   50,  178,   50,
       61,   61,   61,   61,   61,   61,   61,   61,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   81,   81,
       84,   84,   84,   97,   97,  100,  100,  100,  102,  178,
      102,  102,  102,  102,  102,  114,  114,  115,  115,  115,
      116,  116,  116,  116,  116,  129,  178,  129,  129,  129,
      129,  129,  139,  139,  147,  147,  159,  159,  163,  163,

      171,  171,  174,  174,  176,  176,  177,  177,    3,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178
    } ;

static yyconst flex_int16_t yy_chk[882] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,   16,   16,   16,   17,   17,   17,   19,   19,
       21,   21,   25,   26,   28,   27,   31,  174,   28,   29,
       31,  163,   28,   29,   31,   25,  147,   29,   30,  129,

       16,  115,   30,   17,   48,   48,   30,   26,   25,   27,
       49,   49,   49,   49,   30,   31,  114,   29,  102,   25,
       96,   96,   34,   84,   16,   33,   34,   17,   23,   33,
       34,   76,   23,   33,  126,  126,   23,   23,   23,   31,
       30,   29,   34,   58,   23,   23,   23,   23,   23,   23,
       57,   32,   50,   35,   33,   32,   23,   35,   60,   32,
       61,   35,   60,   44,   61,   40,   60,   34,   61,   60,
       23,   23,   23,   23,   23,   78,   78,   78,   33,   32,
       23,   24,   32,   20,   63,   24,   13,   35,   63,   24,
       24,   24,   63,  138,  138,   63,   12,   24,   24,   24,

       24,   24,   24,   32,   64,    9,   32,    7,   64,   62,
       65,   35,   64,   62,   65,    3,   63,   62,   65,   79,
       79,   79,    0,   24,   24,   24,   24,   24,   62,   66,
       67,   68,   64,   66,   67,   68,    0,   66,   67,   68,
       63,   69,    0,   65,   70,   69,   62,    0,   70,   69,
       71,    0,   70,   62,   71,   66,   64,    0,   71,    0,
        0,   72,    0,    0,   68,   72,    0,   65,   73,   72,
       62,    0,   73,    0,   69,    0,   73,   74,    0,   66,
        0,   74,   82,   82,   82,   74,   85,   86,   68,   87,
       85,   86,   72,   87,   85,   86,   89,   87,   69,   88,

       89,   73,   90,   88,   89,   74,   90,   88,    0,   87,
       90,    0,    0,   92,   93,   91,   72,   92,   93,   91,
        0,   92,   93,   91,    0,   73,    0,   89,   90,   74,
        0,    0,   88,   91,   87,   94,   95,   92,  103,   94,
       95,    0,  103,   94,   95,    0,  103,   93,   99,   99,
       99,   89,   90,  113,  113,  113,   88,    0,   91,  104,
        0,   92,    0,  104,   95,   94,    0,  104,  105,   94,
      103,   93,  105,    0,    0,  104,  105,  106,  108,  107,
        0,  106,  108,  107,  105,  106,  108,  107,   95,   94,
        0,  109,  110,   94,  103,  109,  110,  106,    0,  109,

      110,  104,  107,  111,  112,  117,  108,  111,  112,  117,
      105,  111,  112,  117,    0,  118,    0,  110,    0,  118,
        0,    0,  106,  118,  112,  117,  107,  119,  120,  122,
      108,  119,  120,  122,  111,  119,  120,  122,  123,  118,
      121,  110,  123,    0,  121,  119,  123,  124,  121,  112,
      117,  124,    0,  125,    0,  124,  120,  125,  111,    0,
      121,  125,    0,  118,  130,  131,    0,    0,  130,  131,
      119,  123,  130,  131,  132,  124,    0,    0,  132,  125,
      120,    0,  132,  133,    0,  121,  134,  133,    0,    0,
      134,  133,  130,  131,  134,  123,  135,    0,  136,  124,

      135,  133,  136,  125,  135,  137,  136,  132,    0,  137,
        0,  140,    0,  137,    0,  140,  130,  131,  134,  140,
        0,    0,    0,    0,    0,  137,  133,    0,  136,  141,
      142,  132,  143,  141,  142,    0,  143,  141,  142,    0,
      143,  144,  134,  140,    0,  144,    0,    0,  143,  144,
      137,  142,  136,    0,  145,  148,  146,    0,  145,  148,
      146,  141,  145,  148,  146,  149,    0,  140,    0,  149,
      145,    0,    0,  149,  143,  146,  142,    0,  150,  148,
      151,    0,  150,    0,  151,  141,  150,  152,  151,  153,
      155,  152,    0,  153,  155,  152,  145,  153,  155,    0,

      146,    0,  150,  148,  156,  152,    0,  157,  156,    0,
      151,  157,  156,  158,  161,  157,    0,  158,  161,    0,
        0,  158,  161,  155,  156,  162,  150,  160,  164,  162,
      152,  160,  164,  162,  151,  160,  164,    0,  158,    0,
      161,    0,  165,    0,  166,  162,  165,  155,  166,  156,
      165,  160,  166,    0,    0,    0,    0,    0,    0,    0,
        0,  165,  158,  164,  161,  168,    0,    0,  169,  168,
      162,    0,  169,  168,  170,  160,  169,  166,  170,    0,
      172,    0,  170,    0,  172,  168,  165,  164,  172,  173,
        0,    0,    0,  173,    0,    0,    0,  173,    0,    0,

      169,  166,    0,    0,    0,    0,    0,    0,    0,    0,
      168,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  169,  179,    0,  179,  179,  179,
      179,  179,  179,  179,  179,  180,  180,  180,    0,  180,
      181,  181,  181,  181,  181,  181,  181,  181,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  183,  183,
      184,  184,  184,  185,  185,  186,  186,  186,  187,    0,
      187,  187,  187,  187,  187,  188,  188,  189,  189,  189,
      190,  190,  190,  190,  190,  191,    0,  191,  191,  191,
      191,  191,  192,  192,  193,  193,  194,  194,  195,  195,

      196,  196,  197,  197,  198,  198,  199,  199,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int pfl__flex_debug;
int pfl__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *pfl_text;
#line 1 "scanner.l"
/*****************************************************************************/
/*                                                                           */
/* Copyright notice: please read file license.txt in the NetBee root folder. */
/*                                                                           */
/*****************************************************************************/
#line 9 "scanner.l"

#include "defs.h"
#include "pflexpression.h"
#include "compile.h"
#include "parser.hpp"
#include "utils.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>


#define YY_NO_INPUT
//#define YY_NO_UNPUT
static YY_BUFFER_STATE src_buffer = 0;
static uint32 col = 0; //holds the current column
static uint32 row = 1; //holds the current row


#define UPDATE_LOC \
		do{\
			llocp->first_column = col;\
			llocp->first_line = row;\
			col += strlen(pfl_text);\
			llocp->last_column = col;\
			llocp->last_line = row;\
		}while(0)


//NOTE: these declarations are duplicated in gramm.y, so if you modify them here you need to do the same in the other file
#define YY_DECL int pfl_lex (YYSTYPE *lvalp, YYLTYPE *llocp, struct ParserInfo *parserInfo)
int pfl_error(YYLTYPE *llocp, struct ParserInfo *parserInfo, const char *s);

#line 778 "scanner.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int pfl_lex_destroy (void );

int pfl_get_debug (void );

void pfl_set_debug (int debug_flag  );

YY_EXTRA_TYPE pfl_get_extra (void );

void pfl_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *pfl_get_in (void );

void pfl_set_in  (FILE * in_str  );

FILE *pfl_get_out (void );

void pfl_set_out  (FILE * out_str  );

int pfl_get_leng (void );

char *pfl_get_text (void );

int pfl_get_lineno (void );

void pfl_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int pfl_wrap (void );
#else
extern int pfl_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( pfl_text, pfl_leng, 1, pfl_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( pfl_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( pfl_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, pfl_in))==0 && ferror(pfl_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(pfl_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int pfl_lex (void);

#define YY_DECL int pfl_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after pfl_text and pfl_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 78 "scanner.l"


#line 966 "scanner.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! pfl_in )
			pfl_in = stdin;

		if ( ! pfl_out )
			pfl_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			pfl_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				pfl__create_buffer(pfl_in,YY_BUF_SIZE );
		}

		pfl__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of pfl_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 179 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 178 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 80 "scanner.l"
{UPDATE_LOC; strncpy(lvalp->id, pfl_text, ID_LEN - 1);return PFL_NUMBER;};
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 82 "scanner.l"
{UPDATE_LOC; strncpy(lvalp->id, pfl_text, ID_LEN - 1);return PFL_HEXNUMBER;};
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 84 "scanner.l"
{UPDATE_LOC; strncpy(lvalp->id, pfl_text, ID_LEN - 1);return PFL_MACADDR;};
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 86 "scanner.l"
{UPDATE_LOC; return PFL_MATCHES;};
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 87 "scanner.l"
{UPDATE_LOC; return PFL_CONTAINS;};
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 88 "scanner.l"
{UPDATE_LOC; return PFL_SENSITIVE;};
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 89 "scanner.l"
{return PFL_EXTRACT_FIELDS;};
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 90 "scanner.l"
{UPDATE_LOC; return PFL_RETURN_PACKET;};
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 91 "scanner.l"
{UPDATE_LOC; return PFL_RETURN_PACKET;};
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 92 "scanner.l"
{UPDATE_LOC; return PFL_PORT;};
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 93 "scanner.l"
{UPDATE_LOC; return PFL_PORT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 94 "scanner.l"
{UPDATE_LOC; return PFL_ON;};
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 95 "scanner.l"
{UPDATE_LOC; return PFL_AND;};
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 96 "scanner.l"
{UPDATE_LOC; return PFL_OR;};
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 97 "scanner.l"
{UPDATE_LOC; return PFL_NOT;};
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 98 "scanner.l"
{UPDATE_LOC; return PFL_IN;};
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 99 "scanner.l"
{UPDATE_LOC; return PFL_NOTIN;};
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 100 "scanner.l"
{UPDATE_LOC; return PFL_ANY;}; 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 101 "scanner.l"
{UPDATE_LOC; return PFL_TUNNELED;};
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 102 "scanner.l"
{UPDATE_LOC; return PFL_FULLENCAP;};
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 103 "scanner.l"
{UPDATE_LOC; memcpy( lvalp->id, &pfl_text[1], strlen(pfl_text)-2);   lvalp->id[strlen(pfl_text)-2]='\0';return PFL_STRING;};
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 104 "scanner.l"
{UPDATE_LOC; strncpy(lvalp->id, pfl_text, ID_LEN - 1); return PFL_PROTOCOL;};
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 105 "scanner.l"
{UPDATE_LOC; strncpy(lvalp->id, pfl_text, ID_LEN - 1); return PFL_PROTOFIELD;};
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 106 "scanner.l"
{UPDATE_LOC; strncpy(lvalp->id, pfl_text, 255); return PFL_PROTOCOL_INDEX;};
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 107 "scanner.l"
{UPDATE_LOC; strncpy(lvalp->id, pfl_text, 255); return PFL_PROTOFIELD_INDEX;};
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 108 "scanner.l"
{UPDATE_LOC; strncpy(lvalp->id, pfl_text, 255); return PFL_MULTIPROTOFIELD;};
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 109 "scanner.l"
{UPDATE_LOC; strncpy(lvalp->id, pfl_text, 255); return PFL_PROTOMULTIFIELD;};
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 110 "scanner.l"
{UPDATE_LOC; strncpy(lvalp->id, pfl_text, 255); return PFL_PROTOMULTIFIELD_INDEX;};
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 111 "scanner.l"
{UPDATE_LOC; strncpy(lvalp->id, pfl_text, ID_LEN - 1); return PFL_IPV4ADDR;};
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 112 "scanner.l"
{UPDATE_LOC; return PFL_ADD;};
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 113 "scanner.l"
{UPDATE_LOC; return PFL_ADDADD;};
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 114 "scanner.l"
{UPDATE_LOC; return PFL_SUB;};
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 115 "scanner.l"
{UPDATE_LOC; return PFL_QUESTION;};
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 116 "scanner.l"
{UPDATE_LOC; return PFL_MUL;};
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 117 "scanner.l"
{UPDATE_LOC; return PFL_MULMUL;};
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 118 "scanner.l"
{UPDATE_LOC; return PFL_BWAND;};
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 119 "scanner.l"
{UPDATE_LOC; return PFL_BWOR;};
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 120 "scanner.l"
{UPDATE_LOC; return PFL_BWXOR;};
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 121 "scanner.l"
{UPDATE_LOC; return PFL_BWNOT;};
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 122 "scanner.l"
{UPDATE_LOC; return PFL_SHL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 123 "scanner.l"
{UPDATE_LOC; return PFL_SHR;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 124 "scanner.l"
{UPDATE_LOC; return PFL_AND;};
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 125 "scanner.l"
{UPDATE_LOC; return PFL_OR;};
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 126 "scanner.l"
{UPDATE_LOC; return PFL_NOT;};
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 127 "scanner.l"
{UPDATE_LOC; return PFL_EQ;};
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 128 "scanner.l"
{UPDATE_LOC; return PFL_NE;};
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 129 "scanner.l"
{UPDATE_LOC; return PFL_GT;};
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 130 "scanner.l"
{UPDATE_LOC; return PFL_LT;};
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 131 "scanner.l"
{UPDATE_LOC; return PFL_GE;};
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 132 "scanner.l"
{UPDATE_LOC; return PFL_LE;};
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 133 "scanner.l"
{UPDATE_LOC; return ':';};
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 134 "scanner.l"
{UPDATE_LOC; return '[';};
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 135 "scanner.l"
{UPDATE_LOC; return ']';};
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 136 "scanner.l"
{UPDATE_LOC; return '(';};
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 137 "scanner.l"
{UPDATE_LOC; return ')';};
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 138 "scanner.l"
{UPDATE_LOC; row++; return '\n';};
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 139 "scanner.l"
{UPDATE_LOC; return ',';};
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 140 "scanner.l"
{UPDATE_LOC; return '{';};
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 141 "scanner.l"
{UPDATE_LOC; return '}';};
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 142 "scanner.l"
{UPDATE_LOC;};
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 143 "scanner.l"
pfl_error(llocp, parserInfo, "unrecognized character");
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 146 "scanner.l"
ECHO;
	YY_BREAK
#line 1357 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed pfl_in at a new source and called
			 * pfl_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = pfl_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( pfl_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * pfl_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of pfl_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					pfl_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			pfl_restart(pfl_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) pfl_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 179 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 179 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 178);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					pfl_restart(pfl_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( pfl_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve pfl_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void pfl_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        pfl_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            pfl__create_buffer(pfl_in,YY_BUF_SIZE );
	}

	pfl__init_buffer(YY_CURRENT_BUFFER,input_file );
	pfl__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void pfl__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		pfl_pop_buffer_state();
	 *		pfl_push_buffer_state(new_buffer);
     */
	pfl_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	pfl__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (pfl_wrap()) processing, but the only time this flag
	 * is looked at is after pfl_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void pfl__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	pfl_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE pfl__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) pfl_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pfl__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) pfl_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in pfl__create_buffer()" );

	b->yy_is_our_buffer = 1;

	pfl__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with pfl__create_buffer()
 * 
 */
    void pfl__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		pfl_free((void *) b->yy_ch_buf  );

	pfl_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a pfl_restart() or at EOF.
 */
    static void pfl__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	pfl__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then pfl__init_buffer was _probably_
     * called from pfl_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void pfl__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		pfl__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void pfl_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	pfl_ensure_buffer_stack();

	/* This block is copied from pfl__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from pfl__switch_to_buffer. */
	pfl__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void pfl_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	pfl__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		pfl__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void pfl_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)pfl_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in pfl_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)pfl_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in pfl_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE pfl__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) pfl_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pfl__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	pfl__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to pfl_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       pfl__scan_bytes() instead.
 */
YY_BUFFER_STATE pfl__scan_string (yyconst char * yystr )
{
    
	return pfl__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to pfl_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE pfl__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) pfl_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in pfl__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = pfl__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in pfl__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up pfl_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		pfl_text[pfl_leng] = (yy_hold_char); \
		(yy_c_buf_p) = pfl_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		pfl_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int pfl_get_lineno  (void)
{
        
    return pfl_lineno;
}

/** Get the input stream.
 * 
 */
FILE *pfl_get_in  (void)
{
        return pfl_in;
}

/** Get the output stream.
 * 
 */
FILE *pfl_get_out  (void)
{
        return pfl_out;
}

/** Get the length of the current token.
 * 
 */
int pfl_get_leng  (void)
{
        return pfl_leng;
}

/** Get the current token.
 * 
 */

char *pfl_get_text  (void)
{
        return pfl_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void pfl_set_lineno (int  line_number )
{
    
    pfl_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see pfl__switch_to_buffer
 */
void pfl_set_in (FILE *  in_str )
{
        pfl_in = in_str ;
}

void pfl_set_out (FILE *  out_str )
{
        pfl_out = out_str ;
}

int pfl_get_debug  (void)
{
        return pfl__flex_debug;
}

void pfl_set_debug (int  bdebug )
{
        pfl__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from pfl_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    pfl_in = stdin;
    pfl_out = stdout;
#else
    pfl_in = (FILE *) 0;
    pfl_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * pfl_lex_init()
     */
    return 0;
}

/* pfl_lex_destroy is for both reentrant and non-reentrant scanners. */
int pfl_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		pfl__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		pfl_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	pfl_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * pfl_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *pfl_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *pfl_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void pfl_free (void * ptr )
{
	free( (char *) ptr );	/* see pfl_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 146 "scanner.l"




void pflcompiler_lex_init(const char *buf)
{
	src_buffer = pfl__scan_string(buf);
}


void pflcompiler_lex_cleanup()
{
	if (src_buffer != NULL)
		pfl__delete_buffer(src_buffer);
	src_buffer = NULL;
}

